version: '3'
services:
  app:
    build: ./build
    volumes:
      - ./app:/app
      - ./home:/home/jovyan
    ports:
      - "8888:8888"
networks:
  default:
    ipam:
      config:
        - subnet: 192.100.1.0/24
